version: 1
env:
  variables:
    NODE_OPTIONS: --max-old-space-size=4096
    NODE_ENV: production
    NODE_VERSION: 20
    VITE_API_URL: ${API_URL}
    VITE_WS_URL: ${WS_URL}
    VITE_APP_ENV: ${APP_ENV}
build:
  commands:
    - npm ci --prefer-offline --no-audit
    - npm cache clean --force
    - echo "VITE_API_URL=$VITE_API_URL" >> .env
    - echo "VITE_WS_URL=$VITE_WS_URL" >> .env
    - echo "VITE_APP_ENV=$VITE_APP_ENV" >> .env
    - npm run build
    - npm run test:ci 