version: '3.8'

services:
  bot:
    build: .
    container_name: gamedin-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: gamedin-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 