# Render configuration for Serafina Discord Bot (Free Tier)
# Documentation: https://render.com/docs/blueprint-spec

# Global environment variables for all services
envVars:
  - key: NODE_ENV
    value: production
  - key: LOG_LEVEL
    value: info
  - key: DB_DRIVER
    value: postgres  # Use PostgreSQL in production
  - key: COMMANDS_SCOPE
    value: global  # Use global commands in production
  - key: BOT_TAGLINE
    value: "Serafina — your comms layer."
  - key: APP_DESCRIPTION
    value: "Serafina routes messages and services. Use /help."

# Main Discord bot service
services:
  - type: web
    name: serafina-bot
    env: node
    region: oregon  # Choose the region closest to your users
    plan: free  # Free tier
    autoDeploy: true  # Auto-deploy on push to main
    buildCommand: |
      pnpm install --frozen-lockfile && \
      pnpm run build
    startCommand: "npm start"
    envVars:
      - key: PORT_HTTP
        value: 10000
      - key: DISCORD_TOKEN
        sync: false  # Will be set in Render dashboard
      - key: DISCORD_CLIENT_ID
        sync: false  # Will be set in Render dashboard
      - key: DISCORD_CLIENT_SECRET
        sync: false  # Required for OAuth
      - key: POSTGRES_URL
        fromDatabase:
          name: serafina-db
          property: connectionString
    healthCheckPath: /healthz
    healthCheckTimeoutInSeconds: 10
    healthCheckIntervalInSeconds: 60
    numInstances: 1

# Database service (PostgreSQL)
databases:
  - name: serafina-db
    databaseName: serafina
    user: serafina
    plan: free  # Free tier (limited to 90 days, then $7/month)
    ipAllowList:
      - ip: 0.0.0.0/0
        comment: Allow all IPs (for Render services)
    # Automatically run migrations on deploy
    initCommands:
      - npm run migrate:db

# Cron jobs (example for periodic tasks)
crons:
  - name: cleanup-temp-files
    schedule: "0 0 * * *"  # Daily at midnight
    command: node dist/scripts/cleanup.js
    envVars:
      - key: NODE_ENV
        value: production
    envVars:
      - key: PORT
        value: 10002
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
