version: 1
env:
  variables:
    NODE_OPTIONS: --max-old-space-size=4096
    NODE_ENV: production
    NODE_VERSION: 20
    DATABASE_URL: ${DATABASE_URL}
    JWT_SECRET: ${JWT_SECRET}
    AWS_REGION: ${AWS_REGION}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
build:
  commands:
    - npm ci --prefer-offline --no-audit
    - npm cache clean --force
    - echo "DATABASE_URL=$DATABASE_URL" >> .env
    - echo "JWT_SECRET=$JWT_SECRET" >> .env
    - echo "AWS_REGION=$AWS_REGION" >> .env
    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
    - npm run build
    - npm run test:ci 